defaults: &defaults
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5

test: &test
  <<: *defaults
  database: butler-api_test

development:
  <<: *defaults
  database: butler-api_development

staging:
  <<: *defaults
  database: butler-api_staging

production:
  <<: *defaults
  database: butler-api
