# heroku pgbackups:url -a butler-api
# pg_restore --verbose --clean --no-acl --no-owner -h localhost -d butler-api_development ~/DOWNLOADS/a118.dump


defaults: &defaults
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5

test: &test
  <<: *defaults
  database: butler-api_test

development:
  <<: *defaults
  database: butler-api_development

staging:
  <<: *defaults
  database: butler-api_staging

production:
  <<: *defaults
  database: butler-api
