defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

test: &test
  <<: *defaults
  database: butler-api_test

development:
  <<: *defaults
  database: butler-api_development
  port: 15432

staging:
  <<: *defaults
  database: butler-api_staging

production:
  <<: *defaults
  database: butler-api
